version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask_app
    restart: always
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://user:password@db:5432/ielts
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ielts
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  postgres_data:
  certs:
